version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@3.0.0
jobs:
  node/test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test:coveralls
workflows:
  clean-node-api:
    jobs:
      - node/test
