version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  node/test:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm run test:coveralls
workflows:
  node-tests:
    jobs:
      - node/test
